{
gROOT->ProcessLine(".x /home/t2k/cvson/rootlogon.C");
    gROOT->ProcessLine(".L /home/t2k/cvson/basicPlotUtil.C");
    gStyle->SetLineWidth(2);
    
    TFile *outf = new TFile("../inputs/Throws/sys_throws_ptheta_rpaStatic_fix_new_100k_nomsyst.root");
    TFile *outffake = new TFile("../inputs/Throws/sys_throws_ptheta_rpaStatic_fix_new_100k_fakesyst.root");
    TProfile *h_Par = (TProfile*)outf->Get("h_Par");
    TProfile *h_Parfake = (TProfile*)outffake->Get("h_Par");
    TH1D *h_Input = (TH1D*)outf->Get("h_Input");
    TH1D *h_Inputfake = (TH1D*)outffake->Get("h_Input");
    Int_t ci;
    ci = TColor::GetColor("#D55E00");
    new TCanvas;
    titleStyle(h_Input);
    h_Input->GetXaxis()->SetTitle("Parameter index");
    h_Input->GetYaxis()->SetTitle("Central value");
    h_Input->GetYaxis()->SetRangeUser(-0.5,2.5);
    h_Input->Draw();
    h_Inputfake->SetMarkerColor(ci);
    h_Inputfake->SetLineColor(ci);
    h_Inputfake->Draw("same");
     TLegend* leg0 = new TLegend(.17, .25, 0.5, .4);
    leg0->SetFillStyle(0);
    leg0->SetBorderSize(0);
    leg0->SetTextSize(18);
    leg0->SetTextFont(43);
    leg0->AddEntry(h_Input, "w/ 2016 systematic errors", "l");
    leg0->AddEntry(h_Inputfake, "w/ improved systematic errors", "l");
    leg0->SetFillStyle(0);
    leg0->Draw();
    gPad->Print("plots/systThrow_comp_input.eps");
    new TCanvas;
    titleStyle(h_Par);
    h_Par->GetXaxis()->SetTitle("Parameter index");
    h_Par->GetYaxis()->SetTitle("Central value");
    //h_Par->GetYaxis()->SetRangeUser(-0.5,2.5);
    h_Par->SetMaximum(2.5);
    h_Par->SetMinimum(-0.5);
    h_Par->Draw();
    //h_Par->GetYaxis()->SetRangeUser(-0.5,2.5);
    //gPad->Modified();
    h_Parfake->SetMarkerColor(ci);
    h_Parfake->SetLineColor(ci);
    h_Parfake->Draw("same");
    h_Par->GetYaxis()->SetRangeUser(-0.5,2.5);
    gPad->Modified();
    leg0->Draw();
    gPad->Print("plots/systThrow_comp_profile.eps");
}
